### ISSUE TITLE
openfng - add new (additional) player score status.

### ISSUE THREAD

**Issue by kolko** [fstd/teeworlds#87]
Make useful activity score for every player. 
For example, every minute divide by 2 old score and add score by last minute.
This status can show who really good player (and join server minute before), and who make score because  play many time on server.

**Comment by fstd** [comment]
At the end of a round, the score is reset anyway.

**Comment by kolko** [comment]
No, wait. 
This statistic is useful for players who join when round is started already.
For example, player1 from start of round get 50 kills.
After this player2 join and make 25kills, player1 make only 5 kills at this time.
And after, player3 join. And player3 can see, what player2 more dangerous warrior than player1 (but standart score: player1 - 55, player2 - 25 can't show this)

**Comment by fstd** [comment]
What you mention is basically a "problem" with any kind of public-server play - people come and go when they feel like it, rather than in an organized way was would happen in a clan war or similar.
I really feel like implementing this will rather piss off people and cause abuse, but well, i figure it could be made optional. But I can't be bothered to work out the actual formula, so:

Say we're in a game which started at time t_0 and has a (team)score limit of s_max. If we are to adjust scoring based on how much of the game time has already elapsed, then naturally we need to know (or at  least guess) when the game will end (calling this time t_end). 
Case a: There is a time limit, so the game will _probably_ end at t_end.  It might end earlier due to the score limit, though.
Case b: There is no time limit, so we really don't know t_end, we could only extrapolate based on the teamscore, s_max and the elapsed time, which would be everything but accurate.

But let's assume we know t_end.  Now a player, who joined at t_1 (which is somewhere between t_0 and t_end), scores, which raises his original score (s_0) by some value X (the amount of which can vary depending on whether it's a freeze, a melt or a sacrifice), multiplied with (your) adjustment factor F (i.e. score s_0 + X*W = new score)

What would you choose F to be, in terms of the mentioned variables (t_0, t_1, t_end, s_0 and s_max)?

If you can come up with something meaningful here, I'll add it as an optional feature (which will default to off, though)

**Comment by fstd** [comment]
> If you can come up with something meaningful here, I'll add it as an optional feature (which will default to off, though)

I declare timeout
